# Generated by Django 5.0.3 on 2024-03-18 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('profile_img', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
