# Generated by Django 5.0.3 on 2024-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_profile', '0005_project_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
